---
-
  gather_facts: false
  hosts: localhost
  name: Deploy Centos 7 VM
  tasks:
    -
      delegate_to: localhost
      name: "Deploy Centos7"
      vmware_guest:
        cluster: "{{ cluster_name }}"
        customization:
          dns_servers:
            - "192.168.0.206"
            - "1.1.1.1"
          hostname: web02
        datacenter: "{{ datacenter_name }}"
        datastore: esxi-Datastore
        folder: "/{{ datacenter_name }}/vm"
        hostname: "{{ vcenter_server }}"
        name: web02
        networks:
          -
            dns_servers: "192.168.0.206"
            gateway: "10.10.0.1"
            ip: "10.10.0.200"
            name: "VM Network"
            netmask: "255.255.255.0"
            type: static
        password: "{{ vcenter_pass }}"
        state: poweredon
        template: "Centos 7 Template x64"
        username: "{{ vcenter_user }}"
        validate_certs: false
        wait_for_ip_address: true
