---
-
  hosts: all
  name: "Vyos Test"
  tasks:
    -
      name: "show configuration on ethernet devices eth0 and eth1"
      vyos_command:
        commands:
          - "show interfaces ethernet"

    -
      vyos_facts:
        gather_subset: all
        gather_network_resources: all
