---
-
  hosts: all
  name: "Test Juniper Connectivity"
  roles:
    - Juniper.junos
  tasks:
    - name: "Configure op script"
      juniper_junos_config:
        config_mode: "private"
        load: "set"
        lines:
          - "set system scripts op file bgp.slax"
      register: response
    - name: "Print the config changes"
      debug:
        var: response.diff_lines
