---
-
  hosts: all
  name: Backup ESXI Config
  tasks:
    -
      name: Sync the Configadfasd
      command: vim-cmd hostsvc/firmware/sync_config

    -
      name: Backup the Config
      command: vim-cmd hostsvc/firmware/backup_config

    -
      name: find most recent backup
      find:
        paths: /scratch/downloads/
        patterns: "*.tgz"
        recurse: yes
        depth: 5
      register: backup_files

    -
      name: debug
      command: ping cloud.gator.local
      
    -
      name: copy files backup repo
      command: scp -i /etc/ssh/keys-root/id_rsa {{ backup_files }}  esxibackup@cloud.gator.local:/volume1/backups/esxi_configs/{{ ansible_date_time.date }}-{{ ansible_host }}.tgz
